packages:
  - packages/*
  - docs
  - playground
  - playground-nuxt

catalog:
  '@floating-ui/dom': ^1.7.4
  '@vue/server-renderer': ^3.5.27
  '@vue/test-utils': ^2.4.6
  async-validator: ^4.2.5
  dayjs: ^1.11.19
  typescript: ^5.7.3
  vite: ^6.0.7
  vitest: ^4.0.18
  vue: ^3.5.27
  vue-router: ^4.6.4
