/**
 * 内置图标集合
 * @description 提供常用的 SVG 图标
 */
import type { IconData } from '../icon'
export declare const IconClose: IconData
export declare const IconCheck: IconData
export declare const IconArrowUp: IconData
export declare const IconArrowDown: IconData
export declare const IconArrowLeft: IconData
export declare const IconArrowRight: IconData
export declare const IconLoading: IconData
export declare const IconSearch: IconData
export declare const IconPlus: IconData
export declare const IconMinus: IconData
export declare const IconInfo: IconData
export declare const IconWarning: IconData
export declare const IconError: IconData
export declare const IconSuccess: IconData
export declare const IconEye: IconData
export declare const IconEyeOff: IconData
export declare const IconCalendar: IconData
export declare const IconTime: IconData
export declare const IconUser: IconData
export declare const IconSettings: IconData
export declare const IconSetting: IconData
export declare const IconHome: IconData
export declare const IconImage: IconData
export declare const IconDocument: IconData
export declare const IconRefresh: IconData
export declare const IconZoomIn: IconData
export declare const IconZoomOut: IconData
export declare const IconDelete: IconData
export declare const IconUpload: IconData
export declare const IconDownload: IconData
export declare const IconFilePdf: IconData
export declare const IconFileExcel: IconData
export declare const IconFileWord: IconData
export declare const IconFileVideo: IconData
export declare const IconFileAudio: IconData
export declare const IconFileTxt: IconData
export declare const IconAttachment: IconData
export declare const IconEdit: IconData
export declare const IconCopy: IconData
export declare const IconStar: IconData
export declare const IconFolder: IconData
export declare const IconFolderOpened: IconData
export declare const IconRobot: IconData
export declare const IconCloseCircle: IconData
export declare const IconCheckCircle: IconData
export declare const IconSend: IconData
export declare const IconSendArrow: IconData
export declare const IconClean: IconData
export declare const IconPaperclip: IconData
export declare const IconMicrophone: IconData
export declare const IconThumbUp: IconData
export declare const IconThumbDown: IconData
export declare const IconSparkles: IconData
export declare const IconShare: IconData
export declare const IconChat: IconData
export declare const IconVideoPlay: IconData
export declare const IconGlobe: IconData
export declare const IconTable: IconData
export declare const IconChartBar: IconData
export declare const IconLaunch: IconData
export declare const IconCode: IconData
export declare const IconStarFilled: IconData
export declare const IconCheckmarkCircle: IconData
export declare const IconPresentation: IconData
export declare const IconDocumentText: IconData
export declare const IconVideoPause: IconData
export declare const IconBook: IconData
export declare const IconLink: IconData
export declare const IconBold: IconData
export declare const IconItalic: IconData
export declare const IconHeading: IconData
export declare const IconFormat: IconData
export declare const builtInIcons: IconData[]
export default builtInIcons
