/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    GlobalConfig: typeof import('./../components/GlobalConfig.vue')['default']
    HeaderBar: typeof import('./../components/HeaderBar.vue')['default']
    MultiTabs: typeof import('./../components/MultiTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/Sidebar.vue')['default']
    YhAiChat: typeof import('@yh-ui/yh-ui')['YhAiChat']
    YhAiFileCard: typeof import('@yh-ui/yh-ui')['YhAiFileCard']
    YhAiMermaid: typeof import('@yh-ui/yh-ui')['YhAiMermaid']
    YhAiThinking: typeof import('@yh-ui/yh-ui')['YhAiThinking']
    YhAiThoughtChain: typeof import('@yh-ui/yh-ui')['YhAiThoughtChain']
    YhAiWelcome: typeof import('@yh-ui/yh-ui')['YhAiWelcome']
    YhAvatar: typeof import('@yh-ui/yh-ui')['YhAvatar']
    YhBreadcrumb: typeof import('@yh-ui/yh-ui')['YhBreadcrumb']
    YhBreadcrumbItem: typeof import('@yh-ui/yh-ui')['YhBreadcrumbItem']
    YhButton: typeof import('@yh-ui/yh-ui')['YhButton']
    YhCard: typeof import('@yh-ui/yh-ui')['YhCard']
    YhCheckbox: typeof import('@yh-ui/yh-ui')['YhCheckbox']
    YhColorPicker: typeof import('@yh-ui/yh-ui')['YhColorPicker']
    YhConfigProvider: typeof import('@yh-ui/yh-ui')['YhConfigProvider']
    YhDatePicker: typeof import('@yh-ui/yh-ui')['YhDatePicker']
    YhDescriptions: typeof import('@yh-ui/yh-ui')['YhDescriptions']
    YhDescriptionsItem: typeof import('@yh-ui/yh-ui')['YhDescriptionsItem']
    YhDivider: typeof import('@yh-ui/yh-ui')['YhDivider']
    YhDrawer: typeof import('@yh-ui/yh-ui')['YhDrawer']
    YhDropdown: typeof import('@yh-ui/yh-ui')['YhDropdown']
    YhDropdownItem: typeof import('@yh-ui/yh-ui')['YhDropdownItem']
    YhDropdownMenu: typeof import('@yh-ui/yh-ui')['YhDropdownMenu']
    YhForm: typeof import('@yh-ui/yh-ui')['YhForm']
    YhFormItem: typeof import('@yh-ui/yh-ui')['YhFormItem']
    YhIcon: typeof import('@yh-ui/yh-ui')['YhIcon']
    YhInput: typeof import('@yh-ui/yh-ui')['YhInput']
    YhMenu: typeof import('@yh-ui/yh-ui')['YhMenu']
    YhOption: typeof import('@yh-ui/yh-ui')['YhOption']
    YhPagination: typeof import('@yh-ui/yh-ui')['YhPagination']
    YhRadioButton: typeof import('@yh-ui/yh-ui')['YhRadioButton']
    YhRadioGroup: typeof import('@yh-ui/yh-ui')['YhRadioGroup']
    YhResult: typeof import('@yh-ui/yh-ui')['YhResult']
    YhSelect: typeof import('@yh-ui/yh-ui')['YhSelect']
    YhSpace: typeof import('@yh-ui/yh-ui')['YhSpace']
    YhSwitch: typeof import('@yh-ui/yh-ui')['YhSwitch']
    YhTable: typeof import('@yh-ui/yh-ui')['YhTable']
    YhTableColumn: typeof import('@yh-ui/yh-ui')['YhTableColumn']
    YhTabPane: typeof import('@yh-ui/yh-ui')['YhTabPane']
    YhTabs: typeof import('@yh-ui/yh-ui')['YhTabs']
    YhTag: typeof import('@yh-ui/yh-ui')['YhTag']
    YhTooltip: typeof import('@yh-ui/yh-ui')['YhTooltip']
    YhTreeNode: typeof import('@yh-ui/yh-ui')['YhTreeNode']
  }
}
