/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    GlobalConfig: typeof import('./../components/GlobalConfig.vue')['default']
    HeaderBar: typeof import('./../components/HeaderBar.vue')['default']
    MultiTabs: typeof import('./../components/MultiTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/Sidebar.vue')['default']
    YhAvatar: typeof import('@yh-ui/yh-ui')['YhAvatar']
    YhBreadcrumb: typeof import('@yh-ui/yh-ui')['YhBreadcrumb']
    YhBreadcrumbItem: typeof import('@yh-ui/yh-ui')['YhBreadcrumbItem']
    YhButton: typeof import('@yh-ui/yh-ui')['YhButton']
    YhColorPicker: typeof import('@yh-ui/yh-ui')['YhColorPicker']
    YhConfigProvider: typeof import('@yh-ui/yh-ui')['YhConfigProvider']
    YhDivider: typeof import('@yh-ui/yh-ui')['YhDivider']
    YhDrawer: typeof import('@yh-ui/yh-ui')['YhDrawer']
    YhDropdown: typeof import('@yh-ui/yh-ui')['YhDropdown']
    YhDropdownItem: typeof import('@yh-ui/yh-ui')['YhDropdownItem']
    YhDropdownMenu: typeof import('@yh-ui/yh-ui')['YhDropdownMenu']
    YhIcon: typeof import('@yh-ui/yh-ui')['YhIcon']
    YhMenu: typeof import('@yh-ui/yh-ui')['YhMenu']
    YhRadioButton: typeof import('@yh-ui/yh-ui')['YhRadioButton']
    YhRadioGroup: typeof import('@yh-ui/yh-ui')['YhRadioGroup']
    YhSwitch: typeof import('@yh-ui/yh-ui')['YhSwitch']
    YhTooltip: typeof import('@yh-ui/yh-ui')['YhTooltip']
    YhTreeNode: typeof import('@yh-ui/yh-ui')['YhTreeNode']
  }
}
